### ISSUE TITLE
Update the jquery autocomplete avoid errors

### ISSUE THREAD

**Issue by Mte90** [rubengc/cmb2-field-ajax-search#3]
I was trying this fields but was not working on wordpress 4.8.
I saw that error on console:
```
devbridgeAutocomplete is not a function
```
So I updated the library in the package from 1.2.27 to 1.4.1 and now everything is working :-)
